Adding Authorization to CoreChat-Auth
oyindonesia/tusd pull request #3
Opened 2018-11-26 06:54 UTC by dydanz

2018-11-26 07:16 UTC, andrisasuke commented
Comment

2018-11-26 07:19 UTC, okyfirmansyah requested changes

2018-11-26 07:19 UTC, okyfirmansyah commented on unrouted_handler.go
> +
missing '}' bro

2018-11-26 07:22 UTC, andrisasuke requested changes

2018-11-26 07:22 UTC, andrisasuke commented on unrouted_handler.go
> +func AuthorizeCoreChatClient(token string) *httpAuthResponseMsg {
Method ini dipake di tmpat lain ato file lain gk?  Kalo cuma dipake disini diawali huruf kecil namanya. Biar jd private.  

Apa gk sebaiknya return nya boolean true/false? kan cuma ngecek message returnnya authorized or not.

2018-11-26 07:24 UTC, dydanz commented on unrouted_handler.go
> +func AuthorizeCoreChatClient(token string) *httpAuthResponseMsg {
ini baru coba2 pak. isiinya tested, tp in overall function inside tusd lom gw coba run. masih trace gmn cara dapat `x-oy-authorization` pas tusd-client send upload request

2018-11-26 12:51 UTC, andrisasuke commented on unrouted_handler.go
> +func AuthorizeCoreChatClient(token string) *httpAuthResponseMsg {
Clientnya mesti add header tsb pas create request.

2018-12-10 07:48 UTC, andrisasuke requested changes

2018-12-10 07:48 UTC, andrisasuke commented on unrouted_handler.go
> +    req, err := http.NewRequest("GET", "http://172.13.3.68/api/v1/auth/authenticate", nil)
auth host name nya dimasukin ke Flag aja biar configurable.

2018-12-12 04:40 UTC, merged